### ISSUE TITLE
Tjenestekatalog - oppdatere med nye felter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#103]
- [ ] Oppdatere parser

- [ ] Oppdatere fulltext-search

- [ ] Oppdatere frontend sammendragsbokser

- [ ] Oppdatere frontend detaljeside
