### ISSUE TITLE
Designplukk for informasjonsmodeller

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#111]
Se designskisser:
https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/detail-structure-default.html

- [x] Farger av bakgrunn elementer (skal være lilla): catalog-infomodel-lighter #F4F0F7
![image](https://user-images.githubusercontent.com/39513382/101458722-8870a400-3937-11eb-9549-32754a7f0189.png)

- [x] Farger på lenker (skal være lilla): catalog-infomodel-dark #593380
![image](https://user-images.githubusercontent.com/39513382/101458862-bce46000-3937-11eb-90ec-90bd744fb336.png)

- [x] Farger på overskrifter (skal være lilla): catalog-infomodel-dark #593380
![image](https://user-images.githubusercontent.com/39513382/101458904-cb327c00-3937-11eb-9d09-a30e62c3ac29.png)

- [x] Mangler punktlisteikoner (bulletpoints, fylte-piler og ufylte piler)
Lenke til ikoner: https://drive.google.com/drive/folders/1q4ialddr9NarrXXPXcZixS0IS0tlJv-0?usp=sharing
![image](https://user-images.githubusercontent.com/39513382/101459075-0d5bbd80-3938-11eb-8770-ed812ee96d93.png)

- [x] Overskrifter skal være i bold, mens model properties (attribuitter, roller osv) skal ikke være i bold
![image](https://user-images.githubusercontent.com/39513382/101466981-09349d80-3942-11eb-9f18-0ced74c4a42b.png)

- [x] Ikke valgte-faner skal ha lillafarge: catalog-infomodel-dark #593380
- [x] Strek under faner skal ha lilla farge: catalog-infomodel-light: #E4D5F2
![image](https://user-images.githubusercontent.com/39513382/101460791-56ad0c80-393a-11eb-9ce3-62ec6ac39d26.png)

**Comment by lillelars** [comment]
Denne ser veldig bra ut nå. Testet i chrome og edge, i staging.
