### ISSUE TITLE
Håndtering av Triple store (vår Fuseki)

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#150]
Fuseki må tømmes nesten 2 ganger i uka. Vi må finne ut hvordan vi skal håndtere dette fremover.
Vi trenger en måte å gjøre SPARQL spørrnger på. Hvordan?

- [x] Vi må utforske hva vi skal gjøre med Triple store (Fuseki). Skal vi bytte?

- [x] Sette opp lokalt og teste ulike muligheter (Alex?) Timebokse POC til: 2dager.
fungerer som ønsket. Har funksjoner for å komprimere eksisterende datasett. Utfordring: Hver gang vi komprimerer, vokser filene. Har vi f.eks en måte å slette gamle filer har vi en potensielt løsning. Kan vi sette opp et API som håndterer dette?

Potensiell løsning nr 2 (hvis vi ikke får til med Fuseki):
Droppe triple store

- [x] POC på en annen triple store 
- Nils Ove, Hans Olav, Stig tar ansvar for å komme opp med en strategi for håndtering av dette videre.

- [x] Implementere ny triple store

- [ ] ETL

# Alternativer
- Virtuoso open source edition: http://vos.openlinksw.com/owiki/wiki/VOS

**Comment by valosnah** [comment]
fdk-sparql-service deployet i staging, denne har Alex' versjon av fuseki, som har sett ut til å ha løst problemet
Skal kjøres i noen dager for observasjon

**Comment by shenluna** [comment]
Saken er løst og obsertvert ok, ref kommentar over.
