### ISSUE TITLE
Gjennomgang av logging i applikasjonene/GCP

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#187]
Kvaliteten på loggingen varierer for mye fra applikasjon til applikasjon.

- [x] Gjennomgå eksisterende applikasjoner
- [x] Fikse loggnivå slik at dette blir tolket riktig uavhengig av applikasjon
- [x] Ordne dokumentasjon som beskriver hva som forventes

Dokumentasjon:
https://teams.microsoft.com/l/file/e57e875b-1a6e-41c6-8c3e-93d3a54c24ae?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FFDKUtviklingsteam%2FDelte%2520dokumenter%2FIT%2520Infrastruktur%2FApplikasjonskrav%2FLogging.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FFDKUtviklingsteam&serviceName=recent

**Comment by oyvindis** [comment]
Hva med å se på muligheten for å sentralisere all logging gjennom Elastic stack? Da vil både applikasjonslogger og gcp-logger bli søkbart og visuelt synlig på et sted f.eks. med Kibana. Man kan jo ta det gradvis f.eks. et par applikasjoner i første omgang.
