### ISSUE TITLE
[EPIC] Fjerne rabbitmq (under arbeid)

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#656]
Vi ønsker å kvitte oss med rabbitmq, da vi har ganske dårlig kontroll på hva som skjer i rabbitmq. Vi ønsker ikke å kjøre to separate køsystem, som vi gjør i dag.

Dette må gjøres (i prioritert rekkefølge):
- [x] rapportgrafer (API, begrep, Informasjonsmodeller)
- [x] refaktorere fdk-fulltext-search
- [x] refaktorere fdk-model-publisher
- [x] endre oppdateringen til fdk-sparql-service
- [x] bytte ut meldinger til reasoning-service med kafka-meldinger
- [ ] bytte ut meldinger til høsterene med kafka-meldinger
- [ ] migrere resterende rabbitmq-meldinger til kafka og stenge ned rabbitmq

**Comment by KjerstiSteien** [comment]
@NilsOveTen kan du huke av det som er løst her?

**Comment by NilsOveTen** [comment]
Kan vi lukke denne som kopi av #691, eller omvendt?

**Comment by KjerstiSteien** [comment]
Lukker denne som duplikat. Vi beholder #691
