### ISSUE TITLE
[Epic - Begrepskatalog]: styre tilganger lesebruker admingrensesnitt

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-issue-tracker#718]
Avklaringer trengs!
Trenger designskisser

- Mulighet for å styre/velge tilganger til lesebruker (tilgang til å lage utkast og foreslå endringer på begrep)
  - Frontend:
    - [ ] gui
    - [ ] avhukingsboks
    - [ ] validering/sjekk?
  - Backend: 
    - [ ] avklar hvordan løse
    - [ ] ta inn i SSO-token?

Spørsmål:
- [ ] Skal alle lesebrukere ha tilgang til å opprette utkast og kunne foreslå endringer på godkjente begrep?

**Comment by terjesyl** [comment]
@KjerstiSteien denne er også relatert til admin-grensesnitt

**Comment by KjerstiSteien** [comment]
Jeg trodde vi landet på at dette ikke skulle være mulig  å styre fra admin? At det blir for komplekst å håndtere.

**Comment by KjerstiSteien** [comment]
Lukker denne, da dette ikke er funksjonalitet vi trenger. Alle lesebrukere skal kunne foreslå endringer og foreslå nye begrep.
