### ISSUE TITLE
"Exactly-once"-semantikk i meldingsutveksling

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#762]
# Få på plass "exactly-once"-semantikk i meldingssystemet (Rabbit og Kafka)

## Hva
Sørge for at en melding til mottaker er garantert å komme frem til mottaker/konsument nøyaktig én gang og i riktig rekkefølge.
Krever et samarbeid mellom meldingssystemet (Kafka/Rabbit) og applikasjonene som konsumerer og produserer meldinger.

## Hvorfor
Gir mer robuste løp i dataflyten, f.eks. kan vi garantere for at en høsteprosess fullføres og er vellykket.
Mer robust i møte med feil og tjenester som ev. går ned. Kan også håndtere at meldingssystemet går ned.

## Todo
- [ ] Undersøke hva som kreves for å få til "exactly-once", teori og praksis.
- [ ] Undersøke hvilke repoer/tjenester som er berørt.
- [ ] Undersøke muligheter/begrensninger i Kafka vs. Rabbit. Bør vi erstatte Rabbit med Kafka først (se eget issue)?

## Saker som bør løses før denne:
- [ ] [Fase ut RabbitMQ](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/691)
