### ISSUE TITLE
Gå over til Kustomize

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#769]
Vurdere å gå over til Kustomize.

I så fall innføre i [fyll ut liste]:
- [x] fdk-rdf-parser-service

**Høsterene**
- [x] [fdk-informationmodel-harvester](https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester/issues/154)
- [x] [fdk-concept-harvester](https://github.com/Informasjonsforvaltning/fdk-concept-harvester/issues/170)
- [x] [fdk-dataset-harvester](https://github.com/Informasjonsforvaltning/fdk-dataset-harvester/issues/205)
- [x] [fdk-event-harvester](https://github.com/Informasjonsforvaltning/fdk-event-harvester/issues/98)
- [x] [fdk-dataservice-harvester](https://github.com/Informasjonsforvaltning/fdk-dataservice-harvester/issues/165)
- [x] [ fdk-public-service-harvester](https://github.com/Informasjonsforvaltning/fdk-public-service-harvester/issues/118)

**Backend til registrering**

- [x] [concept-catalog](https://github.com/Informasjonsforvaltning/concept-catalog/issues/362)
- [x] [dataset-catalog](https://github.com/Informasjonsforvaltning/dataset-catalog/issues/189)
- [x] [dataservice-catalog](https://github.com/Informasjonsforvaltning/dataservice-catalog/issues/183)

**Andre**

- [x] Informasjonsforvaltning/catalog-comments-service#120
- [x] ~catalog-store~
- [ ] concept-catalog-gui
- [ ] dataservice-catalog-gui
- [x] ~dataservice-publisher-sparql-service~
- [x] ~dataservice-publisher~
- [ ] dataset-catalog-gui
- [ ] dcat-ap-no-validator-cache
- [ ] dcat-ap-no-validator-gui
- [ ] dcat-ap-no-validator-service
- [ ] fdk-admin-gui
- [x] ~fdk-api-endpoints~
- [ ] fdk-cms-service
- [ ] fdk-community-service
- [ ] fdk-community-store
- [x] #1030
- [x] ~fdk-fulltext-search-rabbit-consumer~
- [x] ~fdk-fulltext-search~
- [x] ~fdk-harvest-scheduler~
- [ ] fdk-mail-sender-service
- [x] #1032
- [x] #1033
- [x] #1034
- [x] #1035
- [x] #1036
- [ ] fdk-nginx-altinn-proxy-mock
- [ ] fdk-nginx-altinn-proxy
- [ ] fdk-nginx-community
- [ ] fdk-nginx-dataservices
- [ ] fdk-nginx-enhetsregisteret-proxy-mock
- [ ] fdk-niginx-enhetsregisteret-proxy
- [ ] fdk-nginx-organization-bff
- [ ] fdk-nginx-registration
- [ ] fdk-nginx-search
- [ ] fdk-nginx-sparql
- [ ] fdk-organization-bff
- [ ] fdk-reports-store
- [ ] fdk-sparql-gui
- [x] ~model-publisher~
- [x] Organization Catalog
- [ ] FDK postgresql-sqlproxy config
- [x] ~rdf-prettifier~
- [x] #1029
- [x] [sso](https://github.com/Informasjonsforvaltning/sso/issues/148)
- [ ] static-rdf-server
- [ ] terms-and-condiotions-gui
- [x] terms-and-conditions
- [x] #1028

**Comment by KjerstiSteien** [comment]
@hegeaal det er riktig at fdk-rdf-parser-service fortsatt gjenstår? Er den fortsatt relevant?

**Comment by hegeaal** [comment]
> @hegeaal det er riktig at fdk-rdf-parser-service fortsatt gjenstår? Er den fortsatt relevant?

Nei, det ser ut til at det er løst for fdk-rdf-parser-service. Men mener det gjenstår flere, de er bare ikke skrevet ned her.

**Comment by KjerstiSteien** [comment]
@hegeaal Kan du oppdatere saken med de du vet mangler? Er det andre som har komplett oversikt?

**Comment by hegeaal** [comment]
> @hegeaal Kan du oppdatere saken med de du vet mangler? Er det andre som har komplett oversikt?

Ja, kan prøve å undersøke litt. Antar at det er @valosnah som har best oversikt her.

**Comment by valosnah** [comment]
Ved opprettelse av Kustomize-filer, verifiser at liveness/readiness har paths som gir mening.
Ready burde utføres på en path som bare vil virke når applikasjonen har klart å starte helt opp, og fått kontakt med evt avhengigheter (i.e. _ikke_ /ping).
