### ISSUE TITLE
Aktivere automatisk brukersletting i Datalandsbyen

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#775]
## Målbilde: 
Inaktive brukere skal slettes i henhold til GDPR. 

## Beskrivelse av dagens situasjon:
Brukersletting datalandsbyen er per i dag deaktivert. 

## TODO:
- [ ] Beskrive hvilke kriterier som gjør at en bruker regnes som inaktiv, i samarbeid med Livar Bergheim. 
- [ ] Sette opp regler i henhold til kriteriene som ble beskrevet gjennom punktet over. 
- [ ] Aktivere jobben. 
- [ ] Publisere en post om endringen i Datalandsbyen: https://datalandsbyen.norge.no/category/14/datalandsbyen

**Comment by KurtStian** [comment]
Inaktive brukere er blitt slettet. Det ble sendt e-post til alle brukerne som ville bli slettet i stedet for en post om endringen  i Datalandsbyen.
Beskrivelse av kriteriene for at en bruker regnes som inaktiv er ikke dokumentert. Jeff har sagt at han kan dokumentere dette på sharepoint.

**Comment by KjerstiSteien** [comment]
@jeffreiffers følger du opp dokumentasjon av dette? Eller er det andre som har innsikt i dette som kunne gjort dokumentasjonsjobben?
