### ISSUE TITLE
Epic: dokumentasjon

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-issue-tracker#875]
### Behov for
- [x] #880

### Use cases
- [x] #879
  - [x] Oversikt over tjenester
  - [x] #878
  - [x] #881
  - [x] Hvilke verktøy og programmer trenger jeg for å begynne (se under)?
  - [x] Hvilke tilganger trenger jeg?
  - [x] ~Hva er RDF?~ (fjerne herfra og løse på info-sidene i stedet for)

- [x] ~For utvikler, kommer tilbake til repo, lenge siden sist~
  - [x] ~Småting for å få ting til å funke (portal og env) (oppdatere READMEs) (?)~
    - Bør oppdatere READMEs ved behov
  - [x] ~I JS-prosjekter: riktig node-versjon og env-variabler (?)~
  - [x] ~Sjekke at versjoner er i synk med Dockerfile, compose, package etc. (?)~

- [x] #877
  - [x] #882
    - Pyenv
    - Poetry
    - Nox
  - [x] #884
    - ???
  - [x] #885
    - ???
  - [x] #886
    - ???
  - [x] #883
    - ???
  - [ ] ~RDF-utilities~ (?)

- [x] Trenger kontekst for hvorfor en avgjørelse er tatt: Sette opp ADRs-repo

- [x] Utvikler trenger oversikt over hvor dokumentasjon og prosedyrer er beskrevet (landingssiden)

- [x] ~Ekstern bruker skal ta i bruk Felles Datakatalog og trenger teknisk dokumentasjon~
  - Tas senere

Vi har arkitekturtegning, men den er ikke oppdatert. Foreslår at vi oppretter eget issue på å oppdater arkitekturtegningen sånn at denne saken kan lukkes uavhengig av det.

Use case: Teamet trenger arkitektur-tegninger til møter, vurderinger og avgjørelser
- #985

**Comment by KjerstiSteien** [comment]
@terjesyl Kan du sjekke om sakene som er avhuket faktisk er løst og lukke sakene?
