### ISSUE TITLE
Legge ned datafabrikken

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-issue-tracker#914]
Slagplan for å slå av datafabrikken: 
- [x] Informasjonsforvaltning/fdk-portal#1980
- [x] Fjerne lenker som viser til datafabrikken fra data.norge.no og datalandsbyen. - 15. april
- [x] Bestille/flytte sertifikat og DNS-endringer - 25. april
- [x] Redirecte direkte fra alle datafabrikkens sider til data.norge.no (http og DNS. Sertifikatet flyttes til FDK. DNS flyttes til data.norge.no) -  30. april (Bestilt)
- [x] Ta ned pods i GCP
- [x] Slette GCP-prosjektene for datafabrikken. - 30. april
- [x] Ta ned strapi for Datafabrikken (produksjon) (Jeff uke 18)
- [x] Legge ned datafabrikken i (produksjon) (Jeff uke 18)
- [x] Legge ned juridisk veileder. (produksjon) (Jeff uke 18)
- [x] Fjerne datafabrikk-urlen fra konfig av datalandsbyen og fulltekstsøk. (Jeff uke 18)
- [x] Arkivere repoene for datafabrikken. - 3. april

**Comment by valosnah** [comment]
DNS-endring utføres 30.4 kl 09:00

**Comment by valosnah** [comment]
Alle datafabrikken-prosjektene er skrudd av, og slettes om 30 dager

**Comment by pooriamehregan** [comment]
Er vi ferdig med migreringen her @valosnah? Og kan dette lukkes i så fall? @KjerstiSteien
