### ISSUE TITLE
FDK må produsere og konsumere korrekt datasettbeskrivelser fra spesifikasjon

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-issue-tracker#92]
Våre egne endepunkt må validere - bruk:
https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-service

- [ ] Dataset-catalog må oppdateres til å produsere korrekt dcat-ap-no 2.0 (=> fdk-dataset-harvester kan slite med å høste dette korrekt)

- [ ] fdk-dataset-harvester må høste korrekt dcat-ap-no 2.0 (=> fdk-rdf-parser må håndtere dette korrekt)

- [ ] fdk-dataset-harvester må høste korrekt dcat-ap-no 1.1(=> fdk-rdf-parser må håndtere dette korrekt)

- [ ] fdk-dataservice-harvester må høste korrekt dcat-ap-no 2.0

- [ ] fdk-concept-harvester må høste korrekt SKOS-ap-no 1.03

- [ ] All denne informasjon må vises korrekt i portal
