### ISSUE TITLE
EPIC: Forbedre brukeropplevelse på data.norge.no

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-issue-tracker#952]
TODO: legge inn beskrivelse...

Alle implementasjon saker skal trusselmodelleres [(Threat modellering)](https://digdir.sharepoint.com/:u:/r/sites/FDKUtviklingsteam/SitePages/Threat-modelling.aspx?csf=1&web=1&e=AAC4aO)

- [ ] Oppsummering brukerundersøkelse

- [ ] Enklere og bedre søk ved bruk av AI/LLM-søk
    - [ ] https://github.com/Informasjonsforvaltning/fdk-frontend/issues/70
    - [ ] https://github.com/Informasjonsforvaltning/fdk-llm-search-service/issues/1
    - [ ] https://github.com/Informasjonsforvaltning/fdk-llm-search-service/issues/2
    
- [ ] Forbedre dokumentasjon og veiledning    
    - [ ] Komme i gang og veiledning på hoved siden til data.norge.no
    - [ ] Use-cases på hoved siden til data.norge.no
    - [ ] Kategorisering (temaer) på hoved siden til data.norge.no
    
- [ ] Forbedre finnbarhet på nett
    - [ ] SEO data.norge.no - Sitemap
    - [ ] SEO data.norge.no - Metadata og generelle forbedringer
    - [ ] Monsido event tracking, heatmaps
    - [ ] Logoer og samarbeidspartnere på hoved siden til data.norge.no

**Comment by KjerstiSteien** [comment]
Lukket etter sjekk med teamet. Saken dekkes av roadmapsak og milestones knyttet til forbedring av data.norge.no
